version: '3'

services:

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    working_dir: /code/server
    command: gunicorn webhook:init_app --reload --worker-class aiohttp.GunicornWebWorker --bind 0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - memcached
#    restart: always

  redis:
    image: redis:6.0.8-alpine
    volumes:
      - ./data:/data
    command: redis-server
    ports:
      - "6379:6379"
    restart: always

  memcached:
    image: memcached:1.6.7-alpine
    ports:
      - "11211:11211"
    restart: always

  subscription:
    build:
      context: .
      dockerfile: docker/subscription/Dockerfile
    working_dir: /code/server
    command: python -u subscribe.py
    depends_on:
      - web
    restart: always