version: '3'

services:
  web: &web
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    command: gunicorn -w 4 webhook:init_app --reload --worker-class aiohttp.GunicornWebWorker --bind 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      -
    restart: always
    entrypoint: /entrypoint.sh
  memcached:
    build:
      context: .
      dockerfile: docker/rabbitmq/Dockerfile
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  celery_worker:
    <<: *web
    command: celery -A bostonGene worker -l info
    ports: []
    depends_on:
      - rabbitmq
    restart: always